const styles = {
  containerItem: {
    background: '#F7F7F7',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    fontFamily: 'Helvetica',
    fontSize: '1em',
  },
  hederItem: {
    color: '#ffffff',
    fontSize: '2em',
    fontWeight: 500,
    textAlign: 'center',
    marginTop: '1em',
    marginBottom: '1em',
    padding: '1em',
    background: '#36A2EB',
    maxHeight: '2em',
    borderRadius: '1em',
    minWidth: '240px',
    maxWidth: '320px',
  },
    chartSection: {
      display: 'flex',
      margin: '1em',
      flexwrap: 'wrap',
      justifyContent: 'center',
    },
    chartItem: {
      display: 'flex',
      width: 'calc(100% / 4)',
      listStyleType: 'none',
      background: '#ffffff',
      border: '2px #e5e5e5',
      boxShadow: '0px 0px 10px 3px #e5e5e5',
      padding: '1em',
      margin: '1em',
      cursor: 'pointer',
      borderRadius: '1em',
      fontFamily: 'Helvetica',
      fontWeight: 400,
      fontSize: '1em',
      textAlign: 'left',
      lineHeight: '140%',
      blockSize: 'fit-content',
      minWidth: '100px',
      maxWidth: '80%',
    },
    presetItem: {
      background: '#ffffff',
      border: '2px #e5e5e5',
      boxShadow: '0px 0px 10px 3px #e5e5e5',
      padding: '1em',
      margin: '1em',
      maxWidth: '60%',
      cursor: 'pointer',
      borderRadius: '1em',
      fontFamily: 'Helvetica',
      fontWeight: 400,
      fontSize: '1em',
      textAlign: 'left',
      lineHeight: '140%',
    },
  };
  
  export default styles;
  